# Reduce dimensionality - UMAPs{#ReducedDimensionality}

## Reload data

```{r echo=FALSE, results='hide', warnings=FALSE}
library(Seurat)
library(tidyverse)
library(here)

filtered_seurat_object_file <- here("data", "GSE234713_CosMx_IBD_seurat_02_rna70_neg4.RDS")
so    <- readRDS(filtered_seurat_object_file) 
```

## Normalisation

```{r message=FALSE}
so <- NormalizeData(so)
```

## Find Highly variable genes.

```{r message=FALSE}
so <- FindVariableFeatures(so, nfeatures = 200)
```

```{r}
VariableFeaturePlot(so)
```

```{r}
head(VariableFeatures(so))
```

## Scale data

```{r message=FALSE}
so <- ScaleData(so) # Just 200 variable features
```

```{r}
so
```

## PCA

```{R message=FALSE}
so <- RunPCA(so, features = VariableFeatures(so))
```

```{r}
so
```

```{r}
so@reductions$pca@cell.embeddings[1:10,1:5]
```

```{r}
DimPlot(so, reduction = "pca", group.by='tissue_sample')
```

## UMAP

```{r}
ElbowPlot(so)
```

```{r message=FALSE}
num_dims <- 15
so <- RunUMAP(so, dims=1:num_dims)
```

```{r}
# you can specify reduction='umap' explicitly
# you can specify reduction='umap' explicitly

# DimPlot(so, group.by='tissue_sample', reduction = 'umap') 
# DimPlot(so, group.by='tissue_sample', reduction = 'umap') 

# But by default, if a umap exists in the object, Dimplot will plot it.
# But by default, if a umap exists in the object, Dimplot will plot it.

DimPlot(so, group.by='tissue_sample') 
```

## Using UMAP to visualise your data

```{r}
DimPlot(so, group.by='tissue_sample')
DimPlot(so, group.by='condition')
DimPlot(so, group.by='tissue_sample', split.by='condition')
```

```{r message=FALSE, warning=FALSE}
FeaturePlot(so, 'nCount_RNA') 
FeaturePlot(so, 'nCount_negprobes') 
```

```{r message=FALSE, warning=FALSE}
so$pc_neg <- so$nCount_negprobes / (so$nCount_negprobes + so$nCount_RNA) * 100
FeaturePlot(so, 'pc_neg') 
```

```{r}
FeaturePlot(so, c('CD74','PIGR','IGHA1','NRG1'), ncol=2 )
```

